from typing import Literal

MangaCategories = Literal['manga' , 'one-shot' , 'doujinshi' , 'novel' , 'manhwa' , 'manhua']

MANGA_GENRES =  Literal [
    'action',
    'adventure',
    'cars',
    'comedy',
    'dementia',
    'demons',
    'drama',
    'ecchi',
    'fantasy',
    'game',
    'gender-bender',
    'harem',
    'hentai',
    'historical',
    'horror',
    'josei',
    'kids',
    'magic',
    'martial-arts',
    'mecha',
    'military',
    'music',
    'mystery',
    'parody',
    'police',
    'psychological',
    'romance',
    'samurai',
    'school',
    'sci-fi',
    'seinen',
    'shoujo',
    'shoujo-ai',
    'shounen',
    'shounen-ai',
    'slice-of-life',
    'space',
    'sports',
    'super-power',
    'supernatural',
    'thriller',
    'vampire',
    'yaoi',
    'yuri',
]